---
title: "Datos Bea"
output: html_notebook
---

https://github.com/us-bea/bea.R/blob/master/beaR_instructions.pdf

```{r}
#install.packages('bea.R')
library(bea.R)
library(tidyverse)

```

```{r}
beaKey 	<- read_file('fuentes/bea_apikey.txt')
```

```{r}
beaSpecs <- list(
  'UserID' = beaKey ,
  'Method' = 'GetData',
  'datasetname' = 'NIPA',
  'TableName' = 'T20305',
  'Frequency' = 'Q',
  'Year' = 'X',
  'ResultFormat' = 'json'
)


beaPayload <- beaGet(beaSpecs)
beaPayload
```

```{r}
beaPayload %>% 
  gather(periodo, valor, 8:ncol(.)) %>% 
  separate(periodo, into = c('year','quarter'),sep = 'Q') %>% 
  mutate(year = str_match(year, pattern = '\\d{4}'))
```

Datos relacionados con [NIPA](https://www.econdb.com/dataset/NIPA/standard-national-income-and-product-accounts-tables/#5006=[5612]&26190=[26200]&to=2019-09-01&from=1929-01-01&h=TIME&v=Series%20description)

```{r}
datos_posibles_FA <- bea.R::beaSearch('FIXEDASSETS',beaKey)
datos_posibles_FA
```


Si queremos por ejemplo los datos de Equipment. Table 1.1.5. Gross Domestic Product

Busco usando filter y me quedo con la columna _apiCall_ que me da el código que necesito

```{r}
datos_posibles_NIPA %>% 
  filter(LineDescription=='Equipment', TableName=='Table 1.1.5. Gross Domestic Product') %>% 
  pull(apiCall)
```

me copio esa linea, remplazo la beaKey, agrego Frquencym year y ResultFormat

```{r}
consumo_capital <- beaGet(list('UserID' = beaKey, 
                             'Method' = 'GetData',
                             'DatasetName' = 'NIPA',
                             'TableName' = 'T70500',
                             'Frequency' = 'A',
                             'Year' = 'X',
                             'ResultFormat' = 'json'))

consumo_capital
```

```{r}
consumo_capital <- consumo_capital %>% 
  gather(., key =year, value=consumo_capital,DataValue_1929:ncol(.)) %>% 
  mutate(year = parse_number(year),
         consumo_capital = consumo_capital*10^as.numeric(UNIT_MULT)) %>% 
  select(line_description=LineDescription, metric_name = METRIC_NAME, year, consumo_capital)

```


### Fixed assets


```{r}
stock_capital <- beaGet(list('UserID' = beaKey,
                             'Method' = 'GetData',
                             'DatasetName' = 'FixedAssets',
                             'TableName' = 'FAAt101',
                             'Frequency' = 'A',
                             'Year' = 'X',
                             'ResultFormat' = 'json'))


stock_capital
```


```{r}
stock_capital <- stock_capital %>% 
  gather(., key =year, value=stock_capital,DataValue_1925:ncol(.)) %>% 
  mutate(year = parse_number(year),
         stock_capital = stock_capital*10^as.numeric(UNIT_MULT)) %>% 
  select(line_description = LineDescription, metric_name = METRIC_NAME, year, stock_capital)
stock_capital
```


```{r}
consumo_capital %>% inner_join(stock_capital,by = c("line_description", "metric_name", "year"))
```




